stages:
  prepare:
    cmd: python3 src/prepare.py
    deps:
      - src/prepare.py
      - data/raw/solar.zip
      - data/raw/PV01.zip
    params:
      - datamodule.data_root
    outs:
      - ${datamodule.data_root}

  preview:
    cmd: python3 src/preview.py
    deps:
      - src/preview.py
      - ${datamodule.data_root}
    params: 
      - datamodule.seed
      - datamodule.data_root
      - datamodule.split
      - datamodule.batch_size
      - datamodule.image_size
    outs:
      - data/preview

  train:
    cmd: python3 src/train.py
    deps:
      - src/train.py
      - data/preview
      - ${datamodule.data_root}
    params: 
      - datamodule
      - train
    outs:
      - lightning_logs:
          persist: true
      - out/model.ckpt

  export:
    cmd: python3 src/export.py
    deps:
      - src/export.py
      - out/model.ckpt
    params:
      - datamodule.batch_size
      - datamodule.image_size
      - train.num_classes
      - export.model_name
    outs:
      - out/${export.model_name}.bentomodel

  evaluate:
    cmd: python3 src/evaluate.py
    deps:
      - src/evaluate.py
      - out/model.ckpt
    params: 
      - datamodule.seed
      - datamodule.data_root
      - datamodule.split
      - datamodule.batch_size
      - datamodule.image_size
      - train
    outs:
      - data/evaluate

  # detect:
  #   cmd: python3 src/detect_tif.py
  #   deps:
  #     - src/detect_tif.py
  #     - out/model.ckpt
  #     - data/raw/nyon.tif
  #   params:
  #     - datamodule.batch_size
  #     - datamodule.image_size
  #     - train.seed
  #     - train.num_classes
  #   outs:
  #     - out/nyon_solar.gpkg

