stages:
  extract_tiles:
    cmd: python3 src/0_extract_tiles.py
    deps:
      - src/0_extract_tiles.py
      - data/raw/swissBOUNDARIES3D_1_5_LV95_LN02.gpkg
    params: 
      - extract_tiles
    outs:
      - data/extracted

  pull_labels:
    cmd: python3 src/1_pull_labels.py
    deps:
      - src/1_pull_labels.py
    outs: 
      - data/labels/annotations.json
    always_changed: true

  prepare:
    cmd: python3 src/2_prepare.py
    deps:
      - src/2_prepare.py
      - data/extracted/tiles
      - data/labels/annotations.json
      - data/raw/solar.zip
      - data/raw/PV01.zip
    params:
      - datamodule.data_root
    outs:
      - ${datamodule.data_root}

  # preview:
  #   cmd: python3 src/3_preview.py
  #   deps:
  #     - src/3_preview.py
  #     - ${datamodule.data_root}
  #   params: 
  #     - datamodule.seed
  #     - datamodule.data_root
  #     - datamodule.split
  #     - datamodule.batch_size
  #     - datamodule.image_size
  #   outs:
  #     - data/preview

  # train:
  #   cmd: python3 src/4_train.py
  #   deps:
  #     - src/4_train.py
  #     - data/preview
  #     - ${datamodule.data_root}
  #   params: 
  #     - datamodule
  #     - train
  #   outs:
  #     - lightning_logs:
  #         persist: true
  #     - out/model.ckpt

  # export:
  #   cmd: python3 src/5_export.py
  #   deps:
  #     - src/5_export.py
  #     - out/model.ckpt
  #   params:
  #     - datamodule.batch_size
  #     - datamodule.image_size
  #     - export.model_name
  #   outs:
  #     - out/${export.model_name}.bentomodel

  # evaluate:
  #   cmd: python3 src/5_evaluate.py
  #   deps:
  #     - src/5_evaluate.py
  #     - out/model.ckpt
  #   params: 
  #     - datamodule.seed
  #     - datamodule.data_root
  #     - datamodule.split
  #     - datamodule.batch_size
  #     - datamodule.image_size
  #     - train
  #   outs:
  #     - data/evaluate

  # detect:
  #   cmd: python3 src/5_detect_tif.py
  #   deps:
  #     - src/5_detect_tif.py
  #     - out/model.ckpt
  #     - data/raw/nyon.tif
  #   params:
  #     - datamodule.batch_size
  #     - datamodule.image_size
  #     - train.seed
  #   outs:
  #     - out/nyon_solar.gpkg

