stages:
  preview:
    cmd: python3 src/preview.py
    deps:
      - src/preview.py
      - data/raw
    params: 
      - datamodule.seed
      - datamodule.data_root
      - datamodule.split
      - datamodule.batch_size
      - datamodule.image_size
    outs:
      - data/preview

  train:
    cmd: python3 src/train.py
    deps:
      - src/train.py
      - data/raw
      - data/preview
    params: 
      - datamodule
      - train
    outs:
      - lightning_logs:
          persist: true
      - out/model.ckpt

  evaluate:
    cmd: python3 src/evaluate.py
    deps:
      - src/evaluate.py
      - out/model.ckpt
    params: 
      - datamodule.seed
      - datamodule.data_root
      - datamodule.split
      - datamodule.batch_size
      - datamodule.image_size
      - train
    outs:
      - data/evaluate

