datamodule:
  seed: 42
  data_root: data/prepared
  split: 0.8
  batch_size: 16
  image_size: 256
  num_workers: 4
  pin_memory: true

# ------------------------------------------------------------------------
# DVC Pipeline Parameters
# ------------------------------------------------------------------------
train:
  seed: 42
  num_classes: 2
  lr: 0.005
  lr_momentum: 0.9
  lr_decay_rate: 0.0005
  lr_sched_step_size: 0.1
  lr_sched_gamma: 0.1
  save_ckpt: false
  es_patience: null
  epochs: 15
  precision: "16-mixed"
  accumulate_grad_batches: null

export:
  model_name: solar_model
