bucket: swissimage-vision

# ------------------------------------------------------------------------
# DVC Pipeline Parameters
# ------------------------------------------------------------------------
prepare:
  src_bucket: swissimage-0.1m  # S3 bucket name
  s3_src_vrt_path: files.vrt  # S3 path to the VRT file
  s3_dest_prepared_path: data/prepared  # S3 path where to save the prepared data
  commune_name: Nyon     # Commune name to be cropped
  commune_x_ratio: 0.66  # Width ratio of the crop for the commune
  commune_y_ratio: 0.75  # Height ratio of the crop for the commune
  tile_size: 1024        # Tile size cropped from the original image in pixels

preprocess:  # Empty for now

train:
  datamodule:          # PyTorch Lightning DataModule parameters
    setup:
      # S3 path to the prepared data (should contain images/ and labels/ folders)
      seed: 42         # Random seed for data split
      split: 0.8       # train = split * total
      batch_size: 16
      image_size: 384  # Image size for the model
    num_workers: 8     # Split evenly between train and val dataloaders
    pin_memory: true
  model:
    seed: 42        # Random seed for model initialization
    num_classes: 2  # No solar panel & solar panel
    trainable_backbone_layers: 3
  training:
    lr: 0.0075
    lr_momentum: 0.9
    lr_decay_rate: 0.0005
    lr_sched_step_size: 5  # Step size (epochs) for learning rate scheduler
    lr_sched_gamma: 0.8    # Multiplicative factor of learning rate decay
    save_ckpt: false       # Save best model checkpoint while training
    es_patience: null      # Early stopping patience, null to disable
    epochs: 5
    precision: "16-mixed"

export:
  model_name: solar_model_gpu
