apiVersion: v1
kind: Pod
metadata:
  name: github-runner
  labels:
    app: github-runner
spec:
  containers:
  - name: github-runner
    image: ghcr.io/heigvd-software-engineering/swissimage-vision/github-runner:latest
    env:
    - name: GITHUB_RUNNER_PAT
      valueFrom:
        secretKeyRef:
          name: github-runner-pat
          key: token
    securityContext:
      runAsUser: 1000
    resources:
      limits:
        cpu: "4"
        memory: "2Gi"
      requests:
        cpu: "4"
        memory: "2Gi"
