apiVersion: v1
kind: Pod
metadata:
  name: github-runner-gpu-$(date +%s)
  labels:
    app: github-runner-gpu-$(date +%s)
spec:
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: 16Gi
  containers:
  - name: github-runner-gpu-$(date +%s)
    image: ghcr.io/heigvd-software-engineering/swissimage-vision/github-runner:latest
    # We mount a shared memory volume for training with PyTorch
    volumeMounts:
    - name: dshm
      mountPath: /dev/shm
    env:
    - name: GITHUB_RUNNER_LABELS
      value: "gpu-runner"
    - name: GITHUB_RUNNER_PAT
      valueFrom:
        secretKeyRef:
          name: github-runner-pat
          key: token
    securityContext:
      runAsUser: 1000
    resources:
      limits:
        cpu: "16"
        memory: "64Gi"
        nvidia.com/gpu: "1"
      requests:
        cpu: "16"
        memory: "64Gi"
        nvidia.com/gpu: "1"

