name: Train and Report

env:
  CML_VERSION: 0.20.0
  NODE_VERSION: 18
  PYTHON_VERSION: 3.12

on:
  # Runs on pull requests
  pull_request:
    paths:
      - .github/workflows/train-and-report.yaml
      - src/**
      - dvc.lock
      - dvc.yaml
      - params.yaml
      - requirements.txt

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow the creation and usage of self-hosted runners
permissions:
  contents: read
  id-token: write

jobs:
  setup-runner:
    runs-on: self-hosted
    container: docker://ghcr.io/iterative/cml:0-dvc3-base1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # - uses: hashicorp/setup-terraform@v3
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: ${{ env.NODE_VERSION }}
      - uses: iterative/setup-cml@v2
        with:
          version: ${{ env.CML_VERSION }}
      - name: Initialize runner on Kubernetes
        env:
          REPO_TOKEN: ${{ secrets.PAT }}
          KUBERNETES_CONFIGURATION: ${{ secrets.KUBECONFIG }}
        run: |
          cml runner \
            --labels="cml-runner" \
            --cloud="kubernetes" \
            --cloud-kubernetes-node-selector="nvidia.com/gpu.present=true" \
            --single

  train-and-report:
    permissions: write-all
    needs: setup-runner
    runs-on: [self-hosted, cml-runner]
    container:
      image: docker://ghcr.io/iterative/cml:0-dvc3-base1
      # Configure the container limits
      options: --cpus 16 --memory 64gb --gpus '"device=0"' --shm-size=38gb
    env:
      AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
      - name: Install dependencies
        run: pip install -r requirements-freeze.txt
      - name: Run DVC pipeline
        run: dvc repro --pull
      - name: Push the outcomes to DVC remote storage
        run: dvc push
      - name: Commit changes in dvc.lock
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Commit changes in dvc.lock
          file_pattern: dvc.lock
        # Node is required to run CML
      # - name: Setup Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: ${{ env.NODE_VERSION }}
      - name: Setup CML
        uses: iterative/setup-cml@v2
        with:
          version: ${{ env.CML_VERSION }}
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch all other Git branches
          git fetch --depth=1 origin main:main

          # Add title to the report
          echo "# Experiment Report (${{ github.sha }})" >> report.md

          # Compare parameters to main branch
          echo "## Params workflow vs. main" >> report.md
          dvc params diff main --md >> report.md

          # Publish the CML report
          cml comment update --target=pr --publish report.md
